export const httpStatusMap = [
  { code: 100, constant: 'CONTINUE', reason: 'Continue' },
  { code: 101, constant: 'SWITCHING_PROTOCOLS', reason: 'Switching Protocols' },
  { code: 102, constant: 'PROCESSING', reason: 'Processing' },
  { code: 103, constant: 'EARLY_HINTS', reason: 'Early Hints' },
  { code: 200, constant: 'OK', reason: 'OK' },
  { code: 201, constant: 'CREATED', reason: 'Created' },
  { code: 202, constant: 'ACCEPTED', reason: 'Accepted' },
  { code: 203, constant: 'NON_AUTHORITATIVE_INFORMATION', reason: 'Non Authoritative Information' },
  { code: 204, constant: 'NO_CONTENT', reason: 'No Content' },
  { code: 205, constant: 'RESET_CONTENT', reason: 'Reset Content' },
  { code: 206, constant: 'PARTIAL_CONTENT', reason: 'Partial Content' },
  { code: 207, constant: 'MULTI_STATUS', reason: 'Multi-Status' },
  { code: 300, constant: 'MULTIPLE_CHOICES', reason: 'Multiple Choices' },
  { code: 301, constant: 'MOVED_PERMANENTLY', reason: 'Moved Permanently' },
  { code: 302, constant: 'MOVED_TEMPORARILY', reason: 'Moved Temporarily' },
  { code: 303, constant: 'SEE_OTHER', reason: 'See Other' },
  { code: 304, constant: 'NOT_MODIFIED', reason: 'Not Modified' },
  { code: 305, constant: 'USE_PROXY', reason: 'Use Proxy' },
  { code: 307, constant: 'TEMPORARY_REDIRECT', reason: 'Temporary Redirect' },
  { code: 308, constant: 'PERMANENT_REDIRECT', reason: 'Permanent Redirect' },
  { code: 400, constant: 'BAD_REQUEST', reason: 'Bad Request' },
  { code: 401, constant: 'UNAUTHORIZED', reason: 'Unauthorized' },
  { code: 402, constant: 'PAYMENT_REQUIRED', reason: 'Payment Required' },
  { code: 403, constant: 'FORBIDDEN', reason: 'Forbidden' },
  { code: 404, constant: 'NOT_FOUND', reason: 'Not Found' },
  { code: 405, constant: 'METHOD_NOT_ALLOWED', reason: 'Method Not Allowed' },
  { code: 406, constant: 'NOT_ACCEPTABLE', reason: 'Not Acceptable' },
  { code: 407, constant: 'PROXY_AUTHENTICATION_REQUIRED', reason: 'Proxy Authentication Required' },
  { code: 408, constant: 'REQUEST_TIMEOUT', reason: 'Request Timeout' },
  { code: 409, constant: 'CONFLICT', reason: 'Conflict' },
  { code: 410, constant: 'GONE', reason: 'Gone' },
  { code: 411, constant: 'LENGTH_REQUIRED', reason: 'Length Required' },
  { code: 412, constant: 'PRECONDITION_FAILED', reason: 'Precondition Failed' },
  { code: 413, constant: 'REQUEST_TOO_LONG', reason: 'Request Entity Too Large' },
  { code: 414, constant: 'REQUEST_URI_TOO_LONG', reason: 'Request-URI Too Long' },
  { code: 415, constant: 'UNSUPPORTED_MEDIA_TYPE', reason: 'Unsupported Media Type' },
  { code: 416, constant: 'REQUESTED_RANGE_NOT_SATISFIABLE', reason: 'Requested Range Not Satisfiable' },
  { code: 417, constant: 'EXPECTATION_FAILED', reason: 'Expectation Failed' },
  { code: 418, constant: 'IM_A_TEAPOT', reason: "I'm a teapot" },
  { code: 419, constant: 'INSUFFICIENT_SPACE_ON_RESOURCE', reason: 'Insufficient Space on Resource' },
  { code: 420, constant: 'METHOD_FAILURE', reason: 'Method Failure' },
  { code: 421, constant: 'MISDIRECTED_REQUEST', reason: 'Misdirected Request' },
  { code: 422, constant: 'UNPROCESSABLE_ENTITY', reason: 'Unprocessable Entity' },
  { code: 423, constant: 'LOCKED', reason: 'Locked' },
  { code: 424, constant: 'FAILED_DEPENDENCY', reason: 'Failed Dependency' },
  { code: 425, constant: 'TOO_EARLY', reason: 'Too Early' },
  { code: 426, constant: 'UPGRADE_REQUIRED', reason: 'Upgrade Required' },
  { code: 428, constant: 'PRECONDITION_REQUIRED', reason: 'Precondition Required' },
  { code: 429, constant: 'TOO_MANY_REQUESTS', reason: 'Too Many Requests' },
  { code: 431, constant: 'REQUEST_HEADER_FIELDS_TOO_LARGE', reason: 'Request Header Fields Too Large' },
  { code: 451, constant: 'UNAVAILABLE_FOR_LEGAL_REASONS', reason: 'Unavailable For Legal Reasons' },
  { code: 500, constant: 'INTERNAL_SERVER_ERROR', reason: 'Internal Server Error' },
  { code: 501, constant: 'NOT_IMPLEMENTED', reason: 'Not Implemented' },
  { code: 502, constant: 'BAD_GATEWAY', reason: 'Bad Gateway' },
  { code: 503, constant: 'SERVICE_UNAVAILABLE', reason: 'Service Unavailable' },
  { code: 504, constant: 'GATEWAY_TIMEOUT', reason: 'Gateway Timeout' },
  { code: 505, constant: 'HTTP_VERSION_NOT_SUPPORTED', reason: 'HTTP Version Not Supported' },
  { code: 507, constant: 'INSUFFICIENT_STORAGE', reason: 'Insufficient Storage' },
  { code: 508, constant: 'LOOP_DETECTED', reason: 'Loop Detected' },
  { code: 510, constant: 'NOT_EXTENDED', reason: 'Not Extended' },
  { code: 511, constant: 'NETWORK_AUTHENTICATION_REQUIRED', reason: 'Network Authentication Required' },
];
